config/routes.rb
require 'sidekiq/web'
Tm::Application.routes.draw do
  
  mount Sidekiq::Web, at: "/q"
  

  devise_for :users

  devise_scope :user do
    match 'register/' => "devise/registrations#new"
    match 'register/:free_plan' => "devise/registrations#new"
    
    
  end
  get 'users/' => 'settings_users#index'
  get 'checklists/' => 'checklist_masters#index'
  get 'checklists/new' => 'checklist_masters#new'
  get 'documents/' => 'libraries#index'
  get 'pricing/' => 'welcome#pricing'
  

  resources :docs  do
    get 'upload_process', :on => :member
    get 'reload', :on => :member
    get 'after_upload', :on => :member
    get 'download', :on => :member 
    put 'assign_users', :on => :member
    put 'assign_libs', :on => :member
    get 'flip', :on => :member
    get 'left', :on => :member
    get 'right', :on => :member
    
    put 'move_to_checklist_items', :on => :member
    put 'review', :on => :member
    get 'show_file', :on => :member
    get 'show_png', :on => :member
    get 'get_secret_key', :on => :member
  end
  resources :libraries do
    post 'name', :on => :member
    resources :docs do
      get 'overwrite', :on => :member
    end
    
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
  end
  resources :contacts do
    get 'export', :on => :collection
    get 'role', :on => :member
    get 'extended', :on => :member
    get 'make_guest', :on => :member
  end
  resources :settings_transactions
  resources :transaction_details do
    resources :transaction_types
  end
  resources :transaction_types do
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
      
    end
    post 'update_name', :on => :member
    put 'check', :on  => :member
  end
  
  resources :transaction_statuses do
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
    post 'update_name', :on => :member
    get 'check', :on  => :member
  end
  resources :mail_texts
  resources :settings_checklists
  resources :checklist_masters do
    post 'sort', :on => :collection
  end
  resources :settings_users do
    post 'save_welcome_template', :on => :collection
    put 'small_update', :on => :member
    put 'dropbox_code', :on => :member
    get 'dropbox_sync', :on => :member
    get 'dropbox_sync_verify', :on => :member
    get 'dropbox_restore', :on => :member
    get 'existing_user', :on => :member
    get 'invitation_mail', :on => :member
    get 'accept_invitation', :on => :member
  end
  resources :mail_templates
  get 'send_test_mail/' => 'mail_templates#test_mail'
  resources :users do
    resources :widgets do
      post 'sort', :on => :collection
    end
    get 'check_pass', :on => :member
    get 'destroy_company', :on => :member
    get 'console', :on => :collection
    post 'profile', :on => :member
    post 'company', :on => :member
    put 'assign_contact', :on => :member
    post 'plan', :on => :member
    get 'company_switch_plan', :on => :member
    post 'upgrade', :on => :member
    get 'lock_company', :on => :member
    get 'lock', :on => :member
    get 'switch_user', :on => :collection
    get 'switch_to_admin', :on => :collection
    
  end
  
  
  resources :checklists do
    resources :checklist_items
  end
  resources :checklist_items do
    post 'sort', :on => :collection
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
    put 'check', :on  => :member
    resources :docs do
      put 'move', :on => :collection
      get 'show_pdf', :on => :member
    end
    
  end
  resources :transactions do
    get :remove_notification, :on => :member
    post :search, :on => :collection
    get :in_location, :on => :member
    get :in_status, :on => :member
    get :in_type, :on => :member
    post :mail_attachment, :on => :member
    post :mail_note, :on => :member
    get :pdf, :on => :member
    get :remove_contact, :on => :member
    put :add_contact, :on => :member
    post :add_new_contact, :on => :collection
    get :lock, :on => :member
    get :autocomplete_user_fullname, :on => :collection
    resources :notes
    resources :docs do
      put 'move', :on => :collection
      get 'overwrite', :on => :member
    end
    
    resources :checklists
  end
  resources :locations do
    post 'name', :on => :member
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
  end
  match 'search/' => 'transactions#search'
  match 'lib/' => 'welcome#lib'
  match 'profile/' => 'welcome#profile'
  match 'dropboxauth/' => 'welcome#dropboxauth', :as => "dropboxauth"
  match 'library' => 'libraries#index'
  match 'dashboard' => 'welcome#dashboard'
  
  
  post 'get_mail' => 'transactions#get_mail'
  get 'te' => 'transactions#te'

	get "home(/:action)", :controller => "pages"

  root :to => 'welcome#index'

end

app/models/doc.rb
class Doc < ActiveRecord::Base
  attr_accessible :file, :user_id, :user_ids, :counter, :review, :users_assigned, :by_mail, :secret_key, :incompatible, :alias, :remote_file_url
  #belongs_to :docable, :polymorphic => true
  has_many :doc_accesses, :dependent => :destroy
  has_many :checklist_items, :through => :doc_accesses
  has_many :libraries, :through => :doc_accesses
  has_many :transactions, :through => :doc_accesses
  has_many :png_docs, :dependent => :destroy
  belongs_to :user
  has_and_belongs_to_many :users
  mount_uploader :file, TransactionFileUploader
  #after_create :make_alias
  #validates_format_of :alias, :with => /^[a-zA-Z\d ]*$/i
  #after_save :make_png
  
  
  
  scope :for_search, lambda { |sp| where("file ILIKE lower(?)", "%#{sp.downcase}%")}
  def filename
    File.basename(file.path)
  end
  
  private
  
  def make_alias
    self.alias = self.filename
    self.save
    #unless self.save!
    #  self.alias = "please_rename_#{Random.rand(21800).to_s}.pdf"
    #  self.save
    #end
  end
  
  
  
 
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name, :user_id, :sorting
  has_many :users
  has_many :contacts
  has_many :attach_contacts
  
  default_scope order('sorting ASC')
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:show_file, :show_png, :reload]
  before_filter :load_commentable, :except => [:reload, :left, :right, :flip, :upload_process, :after_upload, :move_to_checklist_items, :review, :show_file, :show_png]
  
  def create
    filename = params[:file].original_filename
    incompatible = false
    if filename.include?("/") || filename.include?("\\") || filename.include?("<") || filename.include?(">") || filename.include?(":") || filename.include?('"') || filename.include?("|") || filename.include?("?") || filename.include?("*")
      incompatible = true
    end
    @file = @docable.docs.create(:file => params[:file], :user_id => current_user.id, :incompatible => incompatible, :alias => filename)
    if @docable.class.name == 'ChecklistItem'
      @docable.doc_accesses.find_by_doc_id(@file.id).update_attributes(:moved => true)
      @transaction = @docable.checklist.transaction
      @transaction.doc_accesses.find_or_create_by_doc_id(@file.id)
    end
    render :text => @file.id
  end
  
  def flip
    @doc = Doc.find(params[:id])
    #Pdftkw.flip(File.join(Rails.root, "public", @doc.file.url))
    Pdftkw.pdf_action_s3(@doc, "D")
    redirect_to :back
  end
  
  def left
    @doc = Doc.find(params[:id])
    Pdftkw.pdf_action_s3(@doc, "L")
    redirect_to :back
  end
  
  def right
    @doc = Doc.find(params[:id])
    Pdftkw.pdf_action_s3(@doc, "R")
    redirect_to :back
  end
  
  def move
    @docable.doc_accesses.moved.destroy_all

    params[:file_ids].each do |id|
      @doc_access = @docable.doc_accesses.find_or_create_by_doc_id(id)
      @doc_access.update_attributes(:moved => true)
    end if params[:file_ids]
    
    @transaction = @docable.checklist.transaction
  end
  
  def reload
    @doc = Doc.find(params[:id])
    @transaction = @doc.transaction
    render :action => "move"
  end
  
  def update
    @doc = Doc.find(params[:id])
    
    
    if @doc.update_attributes(params[:doc])
      redirect_to :back, notice: 'File was successfully renamed.'
    else
      redirect_to :back, alert: 'Error with file renaming.'
    end
    
  end
  
  def review
    @doc = Doc.find(params[:id])
    checked = !@doc.review?
    @doc.update_attributes( :review => checked )
    
    RecentActivity.create(:transaction_id => params[:transaction_id], 
                          :user_id => current_user.id, 
                          :message =>  "#{checked ? 'Reviewed' : 'Unreviewed'} file #{@doc.filename}")
                          
     @transaction = Transaction.find(params[:transaction_id])
  end
  
  def move_to_checklist_items
    @doc = Doc.find(params[:id])
    @doc.doc_accesses.only_ci.destroy_all
    
    params[:file_ids].each do |id|
      @checklist_item = ChecklistItem.find(id)
      
      @doc_access = @checklist_item.doc_accesses.find_or_create_by_doc_id(params[:id])
      @doc_access.update_attributes(:moved => true)
      
    end unless params[:file_ids].blank?
    @transaction = Transaction.find(params[:transaction_id])
  end
  
  def overwrite
    @doc = Doc.find(params[:id])
    @old_doc = @docable.docs.where(:file => @doc.filename).first
    @old_doc.doc_accesses.each do |da|
      @doc.doc_accesses.find_or_create_by_docable_id_and_docable_type(da.docable_id, da.docable_type)
    end
    @doc.update_attributes(:user_ids => @old_doc.users.map(&:id))
    @old_doc.destroy if @old_doc
    redirect_to :back
  end
  
  def assign_users
    @doc = Doc.find(params[:id])
    params[:file_ids] << @doc.user.id
    @doc.update_attributes(:user_ids => params[:file_ids], :users_assigned => true)
    @transaction = Transaction.find(params[:transaction_id])
  end
  
  def assign_libs
    @doc = Doc.find(params[:id])
    
    params[:file_ids].each do |id|
      DocAccess.where(:doc_id => @doc.id).destroy_all
      @library = Library.find(id)
      @library.doc_accesses.find_or_create_by_doc_id(params[:id])
    end
  end
  
  def destroy
    @doc = Doc.find(params[:id])
    @transaction = Transaction.find(params[:transaction_id])
    RecentActivity.create(:transaction_id => params[:transaction_id], 
                          :user_id =>  current_user.id, 
                          :message =>  "deleted file #{@doc.filename}")
    @doc.destroy
    
  end
  
  def upload_process
    
  end
  
  def show_pdf
    @doc = Doc.find(params[:id])
    @key = 1+Random.rand(21890242423423432190823212)
    @doc.update_attributes(:secret_key => @key.to_s)
  end
  
  def get_secret_key
    @doc = Doc.find(params[:id])
    key = 1+Random.rand(21890242423423432190823212)
    @doc.update_attributes(:secret_key => key.to_s)
    render :text => key
  end
  
  def show_file
    @doc = Doc.find_by_secret_key(params[:id].to_s)
    data = open(@doc.file.url)
    @doc.update_attributes(:secret_key => nil)
    send_file data, :disposition => 'inline', :type=>"application/pdf", :x_sendfile=>true
  end
  
  def show_png
    @doc = Doc.find_by_secret_key(params[:id].to_s)
    @doc.update_attributes(:secret_key => nil)
    #@doc = Doc.find(params[:id])
    render :layout => false
  end
    
  def download
    @doc = Doc.find(params[:id])

    open(@doc.file.url) {|doc|
      tmpfile = Tempfile.new("tmp_#{@doc.filename}")
      File.open(tmpfile.path, 'wb') do |f| 
        f.write doc.read
      end 
      send_file tmpfile.path, :filename => "#{@doc.filename}"
    }   
  end
  
  def after_upload
    @existing_file = false
    @pdf_only = false
    @incompatible = false
    @doc = Doc.find(params[:id])
    @docable = @doc.doc_accesses.first.docable
    @transaction = (@doc.doc_accesses.last.docable.class.name == 'Transaction' || @doc.doc_accesses.last.docable.class.name == 'Library') ? @doc.doc_accesses.last.docable :  @doc.doc_accesses.last.docable.checklist.transaction
    
    PngWorker.perform_async(@doc.id)
    
    
    if @transaction.docs.map(&:alias).select{|c| c==@doc.alias}.length > 1
      @existing_file = true
      @doc.destroy
    end
    
    if @global_company.transaction_details.first.only_pdf? && !@doc.filename.include?(".pdf")
      @pdf_only = true
      @doc.destroy
    end
    
    if @doc.incompatible?
      @incompatible = true
      @doc.destroy
    end
  end
  
  private
  
 
  def load_commentable
    resource, id = request.path.split('/')[1, 2]
    @docable = resource.singularize.classify.constantize.find(id)
  end
    
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/_assign_modal.html.haml
#assign_files.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  = form_tag '/', :remote => true, :id => 'move_files_form', :method => :put do 
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      %h3#myModalLabel Assign Files
    .modal-body
      %p
        %table.table.table-striped.table-condensed
          %thead
            %tr
              %th 
              %th{:style => "width: 150px"} File name
              %th Date
              %th Uploaded by
          %tbody
            - @transaction.docs.each do |doc|
              %tr
                %td
                  = check_box_tag "file_ids[]", doc.id
                %td
                  %i.glyphicon.glyphicon-file.big
                  = link_to doc.filename, ""
                %td= doc.created_at.to_s(:short)
                %td= current_user.name

    .modal-footer
      %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Close
      %button.btn.btn-primary Save changes

app/views/docs/_assign_users.html.haml
- main_uid = []
- user_names = []
- @global_company.users.each do |u|
  - if u.super_admin? || u.p_all?
    - user_names << u.fullname
- doc.users.each do |user|
  - if @transaction.attach_contacts.map(&:user_id).include?(user.id)
    - user_names << user.fullname

%i.glyphicon.glyphicon-user.big{:rel => "tooltip", :title => user_names.uniq.join(", "), :class => "assigned_users"}
%span= "(#{user_names.uniq.length})" # doc.users_assigned? ? "(#{user_names.length})" : "(ALL)"

app/views/docs/_assign_users_process.html.haml
- user_ids = []
- @global_company.users.each do |u|
  - if u.super_admin? || u.p_all?
    - user_ids << u.id
=# render "docs/assign_users", :doc => doc
- unless current_user.real_guest? || disable_access(:update, @transaction)
  .btn-group.assign-users
    %button.btn.btn-default.btn-xs.dropdown-toggle{"data-toggle" => "dropdown"}
      Contacts
      %span.caret
    %ul.dropdown-menu
      - User.where("id IN (?) AND id != ?", @transaction.attach_contacts.map(&:user_id), current_user.id).each do |user|
        - unless user_ids.include?(user.id)
          %li
            - unless doc.users.map(&:id).include?(user.id)
              = link_to ms_link_users(user.fullname, user, doc.users), "#", :class => "multicheck", "data-fileid" => user.id
            - else
              .checked
                %span.glyphicon.glyphicon-ok
                = user.fullname
      %li
        .actions.popup_buttons_container
          = link_to "Save", "#", :class => "btn btn-xs btn-info assign_files_to", "data-url" => assign_users_doc_path(doc)+"?transaction_id=#{@transaction.id}"
          = link_to "Cancel", "#", :class => "close_assign_files btn btn-default btn-xs"

app/views/docs/_doc.html.haml
- doc_file_rand = "rand_doc_#{1+Random.rand(21890232190823212)}"
- dublicate = @transaction.docs.where("docs.file = ? AND docs.created_at < ?", doc.filename, doc.created_at).first
- unless dublicate
  %tr.document{:id => "scroll_#{doc_file_rand}", :class => "delete_#{dom_id(doc)}"}
    %td.name
      %strong
        - if doc.filename.include?("pdf")
          = link_to doc.alias, "#", "data-id" => doc_file_rand, :class => "show_doc_embed_file", "data-key" => get_secret_key_doc_path(doc), "data-iframe" => "iframe_#{dom_id(doc)}"
        - else
          = link_to doc.alias, "#", "data-id" => doc_file_rand, :class => "not_pdf", "data-key" => get_secret_key_doc_path(doc), "data-iframe" => "iframe_#{dom_id(doc)}"
      - if dublicate
        .pull-right
          = link_to "Overwrite", overwrite_transaction_doc_path(@transaction, doc), :class => "btn btn-xs btn-danger"
          = link_to "Cancel", doc_path(doc), :method => :delete, :class => "btn btn-xs cancel_after_close", "data-url" => doc_path(doc)
      = form_for doc, :method => :put, :html => {:class => "hidden_item"} do |f|
        = f.text_field :alias
        = f.submit "save", :class => "btn btm-mini"
        = link_to "cancel", "#", :class => "btn btm-mini show_hide_rename_form", "data-formid" => "#edit_#{dom_id(doc)}"
    %td.checklist
      - if doc.doc_accesses.only_ci.empty?
        = ""
      - else
        = link_to "Assigned", "#", :class => "assigned_checklists", :title => doc_assigned_checklist_items(doc), :rel => 'tooltip'
      .btn-group
        %button.btn.btn-default.btn-xs.dropdown-toggle{"data-toggle" => "dropdown", :disabled => disable_access(:assign_files, @transaction)}
          Checklist
          %span.caret
        %ul.dropdown-menu
          - @transaction.checklist_items.each do |checklist_item|
            %li
              = link_to ms_link_items(checklist_item.name, "only_ci", checklist_item, doc), "#", :class => "multicheck #{'checked' if doc.doc_accesses.only_ci.map(&:docable_id).include?(checklist_item.id)}", "data-fileid" => checklist_item.id
          %li
            .popup_buttons_container
              = link_to "Save", "#", :class => "btn btn-xs btn-default assign_files_to", "data-url" => move_to_checklist_items_doc_path(doc)+"?transaction_id=#{@transaction.id}"
              = link_to icon("share-alt", "Cancel"), "#", :class => "close_assign_files btn btn-xs"
    -#
      %td= doc.user.fullname
      %td= doc.created_at.strftime('%b %d, %Y')
        
 
    %td.review
      - unless @global_company.real_free?
        %input{:type => "checkbox", "checked" => doc.review?, :class => "check_checklist_item", "data-url" => review_doc_path(doc)+"?transaction_id=#{@transaction.id}", :disabled => disable_access(:mark_file, @transaction)}
    %td.actions
      .btn-group
        %button.btn.btn-default.btn-xs.dropdown-toggle{"data-toggle" => "dropdown"}
          Actions
          %span.caret
        %ul.dropdown-menu
          %li= link_to icon("pencil", "Rename"), "#", :class => "show_hide_rename_form", "data-formid" => "#edit_#{dom_id(doc)}"
          - unless disable_access(:delete_files, @transaction)
            %li= link_to icon("trash", "Delete"), doc_path(doc)+"?transaction_id=#{@transaction.id}", :method => :delete, :remote => true, :confirm => "Are you sure?"
            %li= link_to icon_fa("refresh", "Flip 180"), flip_doc_path(doc)
            %li= link_to icon_fa("undo", "Left"), left_doc_path(doc)
            %li= link_to icon_fa("repeat", "Right"), right_doc_path(doc)
            %li= mail_to current_user.email+"?attachment=#{doc.file.url}", icon_fa("file-text", "Send as attachments")
            
          - unless disable_access(:download, @transaction)
            %li= link_to icon("download", "Download"), download_doc_path(doc), :target => "blank"
    - if current_user.super_admin? || current_user.p_all? || @transaction.user == current_user
      %td.contacts{:class => "users_#{dom_id(doc)}"}
          
    
        = render "docs/assign_users_process", :doc => doc
          
        
  %tr
    - if params[:action] == "pdf"
      %td.hidden_item.file_iframe{:colspan => 5, :style => "height: 400px", :id => doc_file_rand, :class => "documentViewer"}
    - else
      %td.hidden_item.file_iframe{:colspan => 7, :id => doc_file_rand}
        %div{:style => "width: 100%; height: 100%;", :frameborder => 0, :id => "iframe_#{dom_id(doc)}"}

app/views/docs/_doc_process.html.haml
%tr{:id => "container_#{params[:id]}"}
  %td{:colspan => 7}
    .progress{:id => params[:id], :style => "width:100%"}
      .progress-bar{:style => "width: 1px"}

app/views/docs/_item_doc.html.haml
- doc_file_rand = "rand_doc_#{1+Random.rand(21890232190823212)}"
%tr
  %td{:style => "#{'border: none;' if i==0 }width: 425px;"}
    %i.glyphicon.glyphicon-file.big
    = link_to doc.filename, "#", "data-id" => doc_file_rand, :class => "show_doc_embed_file"
  %td{:style => "width: 90px;#{'border: none;' if i==0 }"}
    = link_to icon("download", "DL"), download_doc_path(doc), :class => "btn btn-info btn-xs", :target => "blank"
       
  %td{:style => "#{'border: none;' if i==0 }", :class => "users_#{dom_id(doc)}"}
    = render "docs/assign_users_process", :doc => doc
      
      
    
  %td{:style => "#{'border: none;' if i==0 }width: 60px;"}
    .pull-right
      %input{:type => "checkbox"}
%tr
  %td.hidden_item.file_iframe{:colspan => 4, :style => "height: 900px", :id => doc_file_rand}
    %iframe{:src => "http://docs.google.com/gview?url=#{show_file_doc_url(doc)}&embedded=true", :style => "width: 100%; height: 900px", :frameborder => 0}

app/views/docs/_item_doc_process.html.haml
%tr{:id => "container_#{params[:id]}"}
  %td
    .progress{:id => params[:id], :style => "width:140px"}
      .progress-bar{:style => "width: 1px"}
  %td{:style => "width: 211px;"}
    = edit_button "download", "DL"
       
  %td
          
    - for i in (0..3+Random.rand(7)).to_a
      %i.glyphicon.glyphicon-user.big{:rel => "tooltip", :title => "User Name"}
    = edit_button "user", "Add"
  %td
    .pull-right
      %input{:type => "checkbox"}

app/views/docs/_library_doc.html.haml
- doc ||= library_doc
- library = doc.doc_accesses.first.docable
- doc_file_rand = "rand_doc_#{1+Random.rand(21890232190823212)}"
- dublicate = Doc.where("docs.file = ? AND docs.created_at < ? AND doc_accesses.docable_type = 'Library' AND doc_accesses.docable_id = ?", doc.filename, doc.created_at, @global_company.id).includes(:doc_accesses).first
%tr{:id => "current_#{dom_id(doc)}"}
  %td{:id => "scroll_#{doc_file_rand}"}
    %i.glyphicon.glyphicon-file.big
    = link_to doc.filename, "#", "data-id" => doc_file_rand, :class => "show_doc_embed_file", "data-key" => get_secret_key_doc_path(doc), "data-iframe" => "iframe_#{dom_id(doc)}"
    - if dublicate
      .pull-right
        = link_to "Overwrite", overwrite_library_doc_path(library, doc), :class => "btn btn-xs btn-danger"
        = link_to "Cancel", doc_path(doc), :method => :delete, :class => "btn btn-xs cancel_after_close", "data-url" => doc_path(doc)
  %td
    = link_to icon("trash", "D"), doc_path(doc), :disabled => disable_access(:manage, Library.last), :method => :delete, :confirm => "Are you sure?", :class => "btn btn-xs btn-info"
    = link_to icon("download", "DL"), download_doc_path(doc), :class => "btn btn-info btn-xs", :target => "blank"
  -#
    %td
      .btn-group{:disabled => disable_access(:manage, Library.last)}
        %button.btn.btn-info.btn-xs{:disabled => disable_access(:manage, Library.last)}
          = icon("folder", "Category")
        %button.btn.btn-info.btn-xs.dropdown-toggle{"data-toggle" => "dropdown", :disabled => disable_access(:manage, Library.last)}
          %span.caret
        %ul.dropdown-menu
          - @global_company.libraries.each do |lib|
            %li
              = link_to ms_link_items(lib.name, "only_l", lib, doc), "#", :class => "multicheck singlecheck #{'checked' if doc.doc_accesses.only_l.map(&:docable_id).include?(lib.id)}", "data-fileid" => lib.id
          %li
            .popup_buttons_container
              = link_to icon("ok", "Save"), "#", :class => "btn btn-xs btn-info assign_files_to", "data-url" => assign_libs_doc_path(doc)
              = link_to icon("share-alt", "Cancel"), "#", :class => "close_assign_files btn btn-xs"
  %td= "#{doc.user.name}"
  %td
    .pull-right
      = doc.created_at.strftime('%b %d, %Y')
%tr
  %td.hidden_item.file_iframe{:colspan => 7, :id => doc_file_rand}
    %div{:style => "width: 100%; height: 100%;", :frameborder => 0, :id => "iframe_#{dom_id(doc)}"}

app/views/docs/_library_progress.html.haml
%tr{:id => "container_#{params[:id]}"}
  %td{:colspan => 5}
    .progress{:id => params[:id]}
      .progress-bar{:style => "width: 1px"}

app/views/docs/_old_assign_users.html.haml
- main_uid = []
- User.all.each do |u|
  - lp = @transaction.location.location_permissions.find_by_user_id(u.id)
  - if (lp && lp.l2?) || u.super_admin? || u.p_all?
    %i.glyphicon.glyphicon-user.big{:rel => "tooltip", :title => u.fullname, :class => "assigned_users", :style => "color: gray"}
    - main_uid << u.id
- doc.users.each do |user|
  - unless main_uid.include?(user.id) || user == doc.user
    %i.glyphicon.glyphicon-user.big{:rel => "tooltip", :title => user.fullname, :class => "assigned_users"}

app/views/docs/_progress_bar.html.haml
.progress{:id => params[:id]}
  .progress-bar{:style => "width: 1px"}

app/views/docs/_show_pdf.html.haml
%iframe{:src => "http://docs.google.com/gview?url=#{show_file_doc_url(@key)}&embedded=true", :style => "width: 100%; height: 900px", :frameborder => 0}

app/views/docs/show_png.html.haml
- if @doc.png_docs.empty?
  %h1 This isn't ready yet
  = link_to "Open PDF", @doc.file.url, :class => "btn btn-info"
- else
  .docviewer{:style => "text-align: center;", "data-current" => 1, "data-total" => @doc.png_docs.length}
    %br
    = link_to icon("arrow-left", ""), "#", :style => "font-size: 25px;", :class => "docviewerButton", "data-d" => "left"
    = link_to icon("arrow-right", ""), "#", :style => "font-size: 25px;", :class => "docviewerButton", "data-d" => "right"
    %br
    - @doc.png_docs.order("file ASC").each_with_index do |d, i|
      = image_tag d.file.url, "data-n" => i+1, :style => i == 0 ? "" : "display:none;", :class => "docviewerImage"