config/routes.rb
require 'sidekiq/web'
Tm::Application.routes.draw do
  
  mount Sidekiq::Web, at: "/q"
  

  devise_for :users

  devise_scope :user do
    match 'register/' => "devise/registrations#new"
    match 'register/:free_plan' => "devise/registrations#new"
    
    
  end
  get 'users/' => 'settings_users#index'
  get 'checklists/' => 'checklist_masters#index'
  get 'checklists/new' => 'checklist_masters#new'
  get 'documents/' => 'libraries#index'
  get 'pricing/' => 'welcome#pricing'
  

  resources :docs  do
    get 'upload_process', :on => :member
    get 'reload', :on => :member
    get 'after_upload', :on => :member
    get 'download', :on => :member 
    put 'assign_users', :on => :member
    put 'assign_libs', :on => :member
    get 'flip', :on => :member
    get 'left', :on => :member
    get 'right', :on => :member
    
    put 'move_to_checklist_items', :on => :member
    put 'review', :on => :member
    get 'show_file', :on => :member
    get 'show_png', :on => :member
    get 'get_secret_key', :on => :member
  end
  resources :libraries do
    post 'name', :on => :member
    resources :docs do
      get 'overwrite', :on => :member
    end
    
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
  end
  resources :contacts do
    get 'export', :on => :collection
    get 'role', :on => :member
    get 'extended', :on => :member
    get 'make_guest', :on => :member
  end
  resources :settings_transactions
  resources :transaction_details do
    resources :transaction_types
  end
  resources :transaction_types do
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
      
    end
    post 'update_name', :on => :member
    put 'check', :on  => :member
  end
  
  resources :transaction_statuses do
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
    post 'update_name', :on => :member
    get 'check', :on  => :member
  end
  resources :mail_texts
  resources :settings_checklists
  resources :checklist_masters do
    post 'sort', :on => :collection
  end
  resources :settings_users do
    post 'save_welcome_template', :on => :collection
    put 'small_update', :on => :member
    put 'dropbox_code', :on => :member
    get 'dropbox_sync', :on => :member
    get 'dropbox_sync_verify', :on => :member
    get 'dropbox_restore', :on => :member
    get 'existing_user', :on => :member
    get 'invitation_mail', :on => :member
    get 'accept_invitation', :on => :member
  end
  resources :mail_templates
  get 'send_test_mail/' => 'mail_templates#test_mail'
  resources :users do
    resources :widgets do
      post 'sort', :on => :collection
    end
    get 'check_pass', :on => :member
    get 'destroy_company', :on => :member
    get 'console', :on => :collection
    post 'profile', :on => :member
    post 'company', :on => :member
    put 'assign_contact', :on => :member
    post 'plan', :on => :member
    get 'company_switch_plan', :on => :member
    post 'upgrade', :on => :member
    get 'lock_company', :on => :member
    get 'lock', :on => :member
    get 'switch_user', :on => :collection
    get 'switch_to_admin', :on => :collection
    
  end
  
  
  resources :checklists do
    resources :checklist_items
  end
  resources :checklist_items do
    post 'sort', :on => :collection
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
    put 'check', :on  => :member
    resources :docs do
      put 'move', :on => :collection
      get 'show_pdf', :on => :member
    end
    
  end
  resources :transactions do
    get :remove_notification, :on => :member
    post :search, :on => :collection
    get :in_location, :on => :member
    get :in_status, :on => :member
    get :in_type, :on => :member
    post :mail_attachment, :on => :member
    post :mail_note, :on => :member
    get :pdf, :on => :member
    get :remove_contact, :on => :member
    put :add_contact, :on => :member
    post :add_new_contact, :on => :collection
    get :lock, :on => :member
    get :autocomplete_user_fullname, :on => :collection
    resources :notes
    resources :docs do
      put 'move', :on => :collection
      get 'overwrite', :on => :member
    end
    
    resources :checklists
  end
  resources :locations do
    post 'name', :on => :member
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
  end
  match 'search/' => 'transactions#search'
  match 'lib/' => 'welcome#lib'
  match 'profile/' => 'welcome#profile'
  match 'dropboxauth/' => 'welcome#dropboxauth', :as => "dropboxauth"
  match 'library' => 'libraries#index'
  match 'dashboard' => 'welcome#dashboard'
  
  
  post 'get_mail' => 'transactions#get_mail'
  get 'te' => 'transactions#te'

	get "home(/:action)", :controller => "pages"

  root :to => 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:index, :pricing]
  def index
    if user_signed_in?
      if current_user.extra_admin?
        redirect_to "/users/console"
      elsif current_user.real_guest?
        redirect_to "/transactions"
      else
        @dashboard = Dashboard.first() || Dashboard.create()
      end
    else
      redirect_to "/home"
    end
  end
  
  def search
    @transactions = Transaction.for_search(params[:search])
    @docs = Doc.for_search(params[:search])
  end
  
  
  
  def dashboard
    @dashboard = Dashboard.first()
    @dashboard.update_attributes(transactions_summary: false,  transactions_alosing: false,  transaction_added: false, transactions_past: false, recent_activity: false, listings: false)
    params[:file_ids].each do |id|
      @dashboard.update_attributes("#{id}" => true)
    end
    
    
  end
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/profiles/_credit_card.html.haml
.row.defailt_padding.toggle_well_plans.hidden_item
  #card_well.col-md-12.well
    %h4.upgrade_title
    = form_for current_user, :url => upgrade_user_path(current_user), :method => :post, :html => {:id => "upgrade_form"} do |f|
      = f.hidden_field :company_plan
      = f.hidden_field :card_four
      = f.hidden_field :plan_id, :value => "plan10"
      = f.hidden_field :stripe_card_token
      .field
        = f.label :email
        = f.text_field :email, style: "width: 98%", :class => "form-control"
      .field
        = label_tag :card_number, "Credit Card Number "
        = text_field_tag :card_number, nil, name: nil, style: "width: 98%", :class => "form-control"
      .field
        = label_tag :card_code, "Security Code on Card (CVV)"
        = text_field_tag :card_code, nil, name: nil, style: "width: 98%", :class => "form-control"
      .field
        = label_tag :card_month, "Card Expiration"
        %br
        = select_month nil, {add_month_numbers_true: true}, {name: nil, id: "card_month", class: "form-control", style: "width: 200px; float: left; margin-right: 5px;"}
        = select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year", class: "form-control", style: "width: 200px; float: left;"}
      .actions
        %br
        %br
        = f.submit "Subscribe", :class => "btn btn-info"

app/views/welcome/profiles/_guest.html.haml
.row.defailt_padding
  .col-md-12
    %h4 You are currently the guest user. You can request any company admin to add you to the company if you would like to be a full user (via personal off-the-system contacting). You can also start your own company and be its admin to manage your transactions and users.
.row.defailt_padding
  .col-md-12    
    = render "welcome/profiles/user"

app/views/welcome/profiles/_payd.html.haml
.row.defailt_padding
  .col-md-12
    %span.label.label-default 
      Billing plan:
      = @global_company.plan_name
.row.defailt_padding
  .col-md-8
    - if @global_company.disabled?
      %center
        %strong.color_red This Account Is Currently Inactive. Please Contact Us To Resolve.
    - if !@global_company.real_free?
      = "Users added in this month: #{@global_company.users.length}"
      %br
      = "Currently monthly usage: #{number_to_currency @global_company.plan_per_user_monthly}"
      %br
      %br
      %br
      You card ending 
      %strong= @global_company.card_four
      will be billed on 
      = "#{Date.today.at_beginning_of_month.next_month.strftime('%b %d, %Y')}."
      = link_to "Update Credit Card", "#", :href => "#", "data-title" => "Update Credit Card", "data-plan" => (@global_company.plan_name == "Pay Per Transaction" ? "transaction" : "user"), :class => "toggle_on_plans"
      %br
      %br
    
  .col-md-4
    = render "welcome/profiles/user"

.row
  .col-md-12
    %h3 Upgrade to:
= render "welcome/profiles/payment_plans"

app/views/welcome/profiles/_payment_plans.html.haml
.row.defailt_padding
  - DefaultPlan::PLANS[2..6].each_with_index do |p, index|
    .col-md-4
      .well.well-light
        %h2.text-warning= p
        %ul
          %li= "Minimum monthly fee: $#{DefaultPlan::PRICES[index+2]}"
          %li= "Price per User: $#{DefaultPlan::PRICE_PER_USER[index+2]}"
          %li= "Minimum users included: #{DefaultPlan::USERS_INCLUDED[index+2]}"
        %hr
          %p
            %a.btn.btn-success.btn-lg.toggle_on_plans{:href => "#", "data-title" => "Upgrade to #{p}", "data-plan" => index+2}
              %i.glyphicon.glyphicon-ok
              Select plan
              
  .col-md-4
    .well.well-light
      %h2.text-warning Enterprise
      %ul
        %li= "Please contact us for details"
        
      %hr
        %p
          %a.btn.btn-success.btn-lg{:href => "mailto:info@transactionmanagement.com"}
            %i.glyphicon.glyphicon-ok
            Select plan
              
= render "welcome/profiles/credit_card"

app/views/welcome/profiles/_trial.html.haml
.row.defailt_padding
  .col-md-12
    %span.label.label-default 
      Billing plan:
      = @global_company.plan_name
.row.defailt_padding
  .col-md-8
    - if @global_company.disabled?
      %center
        %strong.color_red This Account Is Currently Inactive. Please Contact Us To Resolve.
    - if @global_company.trial_ended?
      %strong.color_red 
        Trial expired please choose billing plan below.
    - if @global_company.users_ended? || @global_company.transactions_ended?
      %center
        %strong.color_red 
          Heads up! You`ve reached limit for your trial account.
          %br
          Upgrade to lift the limit
    - if @global_company.users_included == 0
      %center Unlimited users are included
    - else
      .progress
        %span= "#{@global_company.users.company_users.length - 1} / #{@global_company.users_included} users used"
        .progress-bar{:style => "width: #{bar_width(@global_company.users_included, @global_company.users.company_users.length - 1)}%;"}
    %br
    - if @global_company.transactions_included == 0
      %center Unlimited transactions are included
    - else
    -#
      .progress
        %span= "#{@global_company.transactions.length} / #{@global_company.transactions_included} transactions used"
        .progress-bar{:style => "width: #{bar_width(@global_company.transactions_included, @global_company.transactions.length)}%;"}
    %br
    .progress
      %span= "#{@global_company.trial_days - @global_company.days_from_creation.to_i} days remained"
      .progress-bar{:style => "width: #{bar_width(@global_company.trial_days, @global_company.days_from_creation)}%;"}

  .col-md-4
    = render "welcome/profiles/user"

.row
  .col-md-12
    %h3 Upgrade to full account
= render "welcome/profiles/payment_plans"

app/views/welcome/profiles/_user.html.haml
.well
  .pull-right
  %table
    %tbody
      %tr
        %td
          %i.icon-user
          %strong First Name:
        %td
          = link_to(current_user.first_name, "#", :id => "first_name", "data-type" => "text", "data-pk" => "1", "data-url" => profile_user_path(current_user), "data-original-title" => "Enter first name", :class => "super_editable", :style => "color: #000")
      %tr
        %td
          %i.icon-user
          %strong Last Name:
        %td
          = link_to(current_user.last_name, "#", :id => "last_name", "data-type" => "text", "data-pk" => "1", "data-url" => profile_user_path(current_user), "data-original-title" => "Enter first name", :class => "super_editable", :style => "color: #000")
      %tr
        %td
          %i.glyphicon.glyphicon-envelope
          %strong Email:
        %td
          = link_to(current_user.email, "#", :id => "email", "data-type" => "text", "data-pk" => "1", "data-url" => profile_user_path(current_user), "data-original-title" => "Enter first name", :class => "super_editable", :style => "color: #000")
      - if current_user.super_admin? || current_user.p_all?
        %tr
          %td
            %i.icon-building
            %strong Company:
          %td
            = link_to(current_user.company.name, "#", :id => "company_name", "data-type" => "text", "data-pk" => "1", "data-url" => profile_user_path(current_user), "data-original-title" => "Enter company name", :class => "super_editable", :style => "color: #000")
      - elsif current_user.real_guest?
        %tr
          %td
            %i.icon-building
            %strong Company:
          %td
            = link_to(current_user.contact_company, "#", :id => "contact_company", "data-type" => "text", "data-pk" => "1", "data-url" => profile_user_path(current_user), "data-original-title" => "Enter company name", :class => "super_editable", :style => "color: #000")
      - else
        %tr
          %td
            %i.glyphicon.glyphicon-envelope
            %strong Company:
          %td= current_user.contact_company.blank? ? current_user.company.name : current_user.contact_company   
      %tr
        %td
          %i.glyphicon.glyphicon-user
          %strong Avatar:
        %td
          = link_to "Click for change", "#", :class => "add_avatar"
      %tr.hidden_item.add_avatar_well
        %td{:colspan => 2}
          = form_for @user=current_user, :url => small_update_settings_user_path(current_user), :method => :put, :html => { :multipart => true } do |f|
            = f.file_field :avatar, :style => "width: 98%", :placeholder => "Avatar", :class => "form-control"
            %br
            %br
            %button.btn.btn-info
              %i.glyphicon.glyphicon-ok 
              Save
      %tr
        %td
          %i.icon-lock
          %strong Password:
        %td
          = link_to "Click for change", "#", :class => "add_widget"
      
      %tr.hidden_item.add_widget_well
        %td{:colspan => 2}
          = form_for @user=current_user, :url => small_update_settings_user_path(current_user), :method => :put do |f|
            = f.password_field :password, :style => "width: 98%", :placeholder => "Password", :class => "form-control"
            %br
            %br
            = f.password_field :password_confirmation, :style => "width: 98%", :placeholder => "Password Confirmation", :class => "form-control"
            %br
            %br
            %button.btn.btn-info
              %i.glyphicon.glyphicon-ok 
              Save
      %tr
        %td
          %i.icon-dropbox
          %strong Dropbox backup:
        %td
          = link_to current_user.dropbox_code.blank? ? "Click for setup" : "Click for change", "#", :class => "add_dropbox"
      - unless current_user.dropbox_code.blank?
        %tr
          %td{:colspan => 2}= link_to "Backup New", dropbox_sync_settings_user_path(current_user), :class => "btn btn-info"
        %tr
          %td{:colspan => 2}= link_to "Backup Verify", dropbox_sync_verify_settings_user_path(current_user), :class => "btn btn-info"
        %tr
          %td{:colspan => 2}= link_to "Upload new", dropbox_restore_settings_user_path(current_user), :class => "btn btn-info"
        %tr
          %td{:colspan => 2}
            %hr{:style => "margin:0; padding:0;"}
            %span.login_bar= "Dropbox account: #{DropboxSync.new(:access_token => current_user.dropbox_code).account_info()['email']}"
            %br
            %span.login_bar= "Last backup: #{current_user.last_dropbox_backup.blank? ? 'Never' : current_user.last_dropbox_backup.strftime('%b %d, %Y')}"
      %tr.hidden_item.add_dropbox_well
        %td{:colspan => 2}
          = link_to "Get Dropbox Auth Code", DropboxSync.auth_link, :target => :blank
          %br
          = form_for @user=current_user, :url => dropbox_code_settings_user_path(current_user), :method => :put do |f|
            = f.text_area :dropbox_code, :style => "width: 98%", :rows => 3, :placeholder => "Dropbox Auth Code"
            %br
            %br
            %button.btn.btn-info
              %i.glyphicon.glyphicon-ok 
              Save