config/routes.rb
require 'sidekiq/web'
Tm::Application.routes.draw do
  
  mount Sidekiq::Web, at: "/q"
  

  devise_for :users

  devise_scope :user do
    match 'register/' => "devise/registrations#new"
    match 'register/:free_plan' => "devise/registrations#new"
    
    
  end
  get 'users/' => 'settings_users#index'
  get 'checklists/' => 'checklist_masters#index'
  get 'checklists/new' => 'checklist_masters#new'
  get 'documents/' => 'libraries#index'
  get 'pricing/' => 'welcome#pricing'
  

  resources :docs  do
    get 'upload_process', :on => :member
    get 'reload', :on => :member
    get 'after_upload', :on => :member
    get 'download', :on => :member 
    put 'assign_users', :on => :member
    put 'assign_libs', :on => :member
    get 'flip', :on => :member
    get 'left', :on => :member
    get 'right', :on => :member
    
    put 'move_to_checklist_items', :on => :member
    put 'review', :on => :member
    get 'show_file', :on => :member
    get 'show_png', :on => :member
    get 'get_secret_key', :on => :member
  end
  resources :libraries do
    post 'name', :on => :member
    resources :docs do
      get 'overwrite', :on => :member
    end
    
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
  end
  resources :contacts do
    get 'export', :on => :collection
    get 'role', :on => :member
    get 'extended', :on => :member
    get 'make_guest', :on => :member
  end
  resources :settings_transactions
  resources :transaction_details do
    resources :transaction_types
  end
  resources :transaction_types do
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
      
    end
    post 'update_name', :on => :member
    put 'check', :on  => :member
  end
  
  resources :transaction_statuses do
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
    post 'update_name', :on => :member
    get 'check', :on  => :member
  end
  resources :mail_texts
  resources :settings_checklists
  resources :checklist_masters do
    post 'sort', :on => :collection
  end
  resources :settings_users do
    post 'save_welcome_template', :on => :collection
    put 'small_update', :on => :member
    put 'dropbox_code', :on => :member
    get 'dropbox_sync', :on => :member
    get 'dropbox_sync_verify', :on => :member
    get 'dropbox_restore', :on => :member
    get 'existing_user', :on => :member
    get 'invitation_mail', :on => :member
    get 'accept_invitation', :on => :member
  end
  resources :mail_templates
  get 'send_test_mail/' => 'mail_templates#test_mail'
  resources :users do
    resources :widgets do
      post 'sort', :on => :collection
    end
    get 'check_pass', :on => :member
    get 'destroy_company', :on => :member
    get 'console', :on => :collection
    post 'profile', :on => :member
    post 'company', :on => :member
    put 'assign_contact', :on => :member
    post 'plan', :on => :member
    get 'company_switch_plan', :on => :member
    post 'upgrade', :on => :member
    get 'lock_company', :on => :member
    get 'lock', :on => :member
    get 'switch_user', :on => :collection
    get 'switch_to_admin', :on => :collection
    
  end
  
  
  resources :checklists do
    resources :checklist_items
  end
  resources :checklist_items do
    post 'sort', :on => :collection
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
    put 'check', :on  => :member
    resources :docs do
      put 'move', :on => :collection
      get 'show_pdf', :on => :member
    end
    
  end
  resources :transactions do
    get :remove_notification, :on => :member
    post :search, :on => :collection
    get :in_location, :on => :member
    get :in_status, :on => :member
    get :in_type, :on => :member
    post :mail_attachment, :on => :member
    post :mail_note, :on => :member
    get :pdf, :on => :member
    get :remove_contact, :on => :member
    put :add_contact, :on => :member
    post :add_new_contact, :on => :collection
    get :lock, :on => :member
    get :autocomplete_user_fullname, :on => :collection
    resources :notes
    resources :docs do
      put 'move', :on => :collection
      get 'overwrite', :on => :member
    end
    
    resources :checklists
  end
  resources :locations do
    post 'name', :on => :member
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
  end
  match 'search/' => 'transactions#search'
  match 'lib/' => 'welcome#lib'
  match 'profile/' => 'welcome#profile'
  match 'dropboxauth/' => 'welcome#dropboxauth', :as => "dropboxauth"
  match 'library' => 'libraries#index'
  match 'dashboard' => 'welcome#dashboard'
  
  
  post 'get_mail' => 'transactions#get_mail'
  get 'te' => 'transactions#te'

	get "home(/:action)", :controller => "pages"

  root :to => 'welcome#index'

end

app/models/checklist_item.rb
class ChecklistItem < ActiveRecord::Base
  
  attr_accessible :checklist_id, :name, :checked, :position
  has_many :doc_accesses, :as => :docable, :dependent => :destroy
  
  has_many :docs, :through => :doc_accesses
  belongs_to :checklist
  
  scope :checked_only, where(:checked => true)
  scope :unchecked_only, where("checked IS ? OR checked = ?", nil, false)
  
  after_save :change_checklist
  
  def self.sort_positions!(ids)
    ids.each_with_index do |id, index|
      ChecklistItemMaster.find(id).update_attributes(position: index + 1)
    end
  end
  
  private
  def change_checklist
    self.checklist.update_attributes(:completed => self.checklist.checklist_items.map(&:checked).include?(false) ? false : true )
    transaction = self.checklist.transaction
    #transaction.update_attributes(:lock => true) if !transaction.checklists.map(&:completed).include?(false) && TransactionDetail.first.auto_lock?
  end
  
  
end

app/controllers/checklist_items_controller.rb
class ChecklistItemsController < ApplicationController
  can_edit_on_the_spot
  def create
    @checklist = Checklist.find(params[:checklist_id])
    @transaction = @checklist.transaction
    @checklist_item = @checklist.checklist_items.create( params[:checklist_item] )
  end
  
  def sort
    ChecklistItem.sort_positions!(params[:checklist_item_master])
    render nothing: true
  end
  
  def check
    @checklist_item = ChecklistItem.find(params[:id])
    checked = !@checklist_item.checked?
    @checklist_item.update_attributes( :checked => checked )
    @transaction = @checklist_item.checklist.transaction
    
    
    
    RecentActivity.create(:transaction_id => @transaction.id, 
                          :user_id =>  current_user.id, 
                          :message =>  "#{@checklist_item.checked? ? 'checked' : 'unchecked'} #{@checklist_item.name} of #{@checklist_item.checklist.checklist_master.name}")
  end
  
  def destroy
    @checklist_item = ChecklistItem.find(params[:id])
    @checklist_item.destroy
    
  end
  
end

app/helpers/checklist_items_helper.rb
module ChecklistItemsHelper
end

app/views/checklist_items/_assigned.html.haml
- if current_user.super_admin? || current_user.p_all?
  - docs_collection = checklist_item.docs
- else
  - docs_collection = checklist_item.docs.select{|doc| doc.users.map(&:id).include?(current_user.id) }

= docs_collection.map{|l| link_to(l.filename, show_pdf_checklist_item_doc_path(checklist_item, l)+"?fname=#{l.filename}", :remote => true)}.join(", ").html_safe

app/views/checklist_items/_checklist_item.html.haml
%td.checkbox
  %input{:id => "check_checklist_item_#{dom_id(checklist_item)}",:type => "checkbox", "checked" => checklist_item.checked?, :class => "check_checklist_item", "data-url" => check_checklist_item_path(checklist_item), :disabled => disable_access(:check_off_checklists, @transaction)}
%td.name
  %label{for: "check_checklist_item_#{dom_id(checklist_item)}"}
    = on_the_spot_edit checklist_item, :name, :url => update_attribute_on_the_spot_checklist_items_path
-#
  %td.documents
    .btn-group
      %button.btn.btn-info.btn-xs.dropdown-toggle{"data-toggle" => "dropdown", :disabled => disable_access(:assign_files, @transaction)}
        Documents
        %span.caret
      %ul.dropdown-menu{:id => "ul_#{dom_id(checklist_item)}"}
        = render "checklist_items/files", :checklist_item => checklist_item
          
  %td.assigned{:id => "assigned_to_item#{dom_id(checklist_item)}"}= render "checklist_items/assigned", :checklist_item => checklist_item
 
  %td.actions
    .btn-group
      %button.btn.btn-info.btn-xs.dropdown-toggle{"data-toggle" => "dropdown"}
        Actions
        %span.caret
      %ul.dropdown-menu
        - unless disable_access(:upload_files, @transaction)
          %li= link_to icon("upload", "Upload & Assign"), "#", :upload_path => checklist_item_docs_path(checklist_item), :id => "upload_#{dom_id(checklist_item)}", :upload_container => "assigned_to_item#{dom_id(checklist_item)}", :process_view => "false", :after_view => "checklist_item_upload", :class => "uploader_button"
        - unless disable_access(:add_remove_checklists, @transaction)
          %li= link_to icon("trash", "Delete item"), checklist_item_path(checklist_item), :method => :delete, :remote => true, :confirm => "Are you sure?"

app/views/checklist_items/_file_table.html.haml
- checklist_item.docs.each_with_index do |doc, index|
  = render "docs/item_doc", :doc => doc, :i => index

app/views/checklist_items/_files.html.haml
- checklist_item.checklist.transaction.docs.each do |doc|
  - if doc.users.map(&:id).include?(current_user.id) || current_user.super_admin? || current_user.p_all?
    %li
      = link_to ms_link_items(doc.filename, "only_ci", checklist_item, doc), "#", :class => "multicheck #{'checked' if doc.doc_accesses.only_ci.map(&:docable_id).include?(checklist_item.id)}", "data-fileid" => doc.id
%li
  .popup_buttons_container
    = link_to icon("ok", "Save"), "#", :class => "btn btn-xs btn-info assign_files_to", "data-url" => move_checklist_item_docs_path(checklist_item)
    = link_to icon("share-alt", "Cancel"), "#", :class => "close_assign_files btn btn-xs"

app/views/checklist_items/_form.html.haml
= form_for @checklist_item = ChecklistItem.new(), :url => checklist_checklist_items_path(checklist), :remote => true do |f|
  %table.table.table-condensed.add_checklist_item_well.hidden_item{:id => "form_#{dom_id(checklist)}"}
    %tbody
      %tr
        %td
          = f.text_field :name, :class => "form-control input-xlarge new_checklist_input", :placeholder => "Name"
          = f.submit "Save", :class => "btn new_checklist_input_button", :disabled => "true"
          = link_to "Cancel", "#", :class => "close_checklist_item btn"

app/views/checklist_items/_old_checklist_item.html.haml
%tr
  %td{:style => "width: 10px"}
    %input{:type => "checkbox", "checked" => checklist_item.checked?, :class => "check_checklist_item", "data-url" => check_checklist_item_path(checklist_item)}
  %td{:style => "width: 140px"}
    %i.glyphicon.glyphicon-star-empty
    %strong= checklist_item.name
  %td{:style => "width: 100px"}
    %button.btn.btn-info.btn-xs.uploader_button{:upload_path => checklist_item_docs_path(checklist_item), :id => "upload_#{dom_id(checklist_item)}", :upload_container => "file_table#{dom_id(checklist_item)}", :process_view => "item_doc_process", :after_view => "item_doc" }
      %i.glyphicon.glyphicon-upload 
      U
    =# link_to icon("plus", "A"), "#assign_files", :role => "button", :class => "btn btn-info btn-xs", "data-toggle" => "modal", "data-moveurl" => move_checklist_item_docs_path(checklist_item)
    .btn-group
      %button.btn.btn-info.btn-xs A
      %button.btn.btn-info.btn-xs.dropdown-toggle{"data-toggle" => "dropdown"}
        %span.caret
      %ul.dropdown-menu
        - checklist_item.checklist.transaction.docs.each do |doc|
          %li
            = link_to ms_link_items(doc.filename, "only_ci", checklist_item, doc), "#", :class => "multicheck #{'checked' if doc.doc_accesses.only_ci.map(&:docable_id).include?(checklist_item.id)}", "data-fileid" => doc.id
        %li
          .popup_buttons_container
            = link_to icon("ok", "Save"), "#", :class => "btn btn-xs btn-info assign_files_to", "data-url" => move_checklist_item_docs_path(checklist_item)
            = link_to icon("share-alt", "Cancel"), "#", :class => "close_assign_files btn btn-xs"
            

    =# edit_button "plus", "A"
  %td
    .drag{:id => "drop_upload_#{dom_id(checklist_item)}"}
      Drag n Drop
  %td
  %td
%tr
  %td{:style => "width: 10px"}
  %td{:style => "width: 140px"}
  %td{:colspan => 4}
    %table.table.table-condensed.table-hover{:style => "background-color : transparent;"}
      %tbody{:id => "file_table#{dom_id(checklist_item)}"}
        = render "checklist_items/file_table", :checklist_item => checklist_item
        