config/routes.rb
require 'sidekiq/web'
Tm::Application.routes.draw do
  
  mount Sidekiq::Web, at: "/q"
  

  devise_for :users

  devise_scope :user do
    match 'register/' => "devise/registrations#new"
    match 'register/:free_plan' => "devise/registrations#new"
    
    
  end
  get 'users/' => 'settings_users#index'
  get 'checklists/' => 'checklist_masters#index'
  get 'checklists/new' => 'checklist_masters#new'
  get 'documents/' => 'libraries#index'
  get 'pricing/' => 'welcome#pricing'
  

  resources :docs  do
    get 'upload_process', :on => :member
    get 'reload', :on => :member
    get 'after_upload', :on => :member
    get 'download', :on => :member 
    put 'assign_users', :on => :member
    put 'assign_libs', :on => :member
    get 'flip', :on => :member
    get 'left', :on => :member
    get 'right', :on => :member
    
    put 'move_to_checklist_items', :on => :member
    put 'review', :on => :member
    get 'show_file', :on => :member
    get 'show_png', :on => :member
    get 'get_secret_key', :on => :member
  end
  resources :libraries do
    post 'name', :on => :member
    resources :docs do
      get 'overwrite', :on => :member
    end
    
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
  end
  resources :contacts do
    get 'export', :on => :collection
    get 'role', :on => :member
    get 'extended', :on => :member
    get 'make_guest', :on => :member
  end
  resources :settings_transactions
  resources :transaction_details do
    resources :transaction_types
  end
  resources :transaction_types do
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
      
    end
    post 'update_name', :on => :member
    put 'check', :on  => :member
  end
  
  resources :transaction_statuses do
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
    post 'update_name', :on => :member
    get 'check', :on  => :member
  end
  resources :mail_texts
  resources :settings_checklists
  resources :checklist_masters do
    post 'sort', :on => :collection
  end
  resources :settings_users do
    post 'save_welcome_template', :on => :collection
    put 'small_update', :on => :member
    put 'dropbox_code', :on => :member
    get 'dropbox_sync', :on => :member
    get 'dropbox_sync_verify', :on => :member
    get 'dropbox_restore', :on => :member
    get 'existing_user', :on => :member
    get 'invitation_mail', :on => :member
    get 'accept_invitation', :on => :member
  end
  resources :mail_templates
  get 'send_test_mail/' => 'mail_templates#test_mail'
  resources :users do
    resources :widgets do
      post 'sort', :on => :collection
    end
    get 'check_pass', :on => :member
    get 'destroy_company', :on => :member
    get 'console', :on => :collection
    post 'profile', :on => :member
    post 'company', :on => :member
    put 'assign_contact', :on => :member
    post 'plan', :on => :member
    get 'company_switch_plan', :on => :member
    post 'upgrade', :on => :member
    get 'lock_company', :on => :member
    get 'lock', :on => :member
    get 'switch_user', :on => :collection
    get 'switch_to_admin', :on => :collection
    
  end
  
  
  resources :checklists do
    resources :checklist_items
  end
  resources :checklist_items do
    post 'sort', :on => :collection
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
    put 'check', :on  => :member
    resources :docs do
      put 'move', :on => :collection
      get 'show_pdf', :on => :member
    end
    
  end
  resources :transactions do
    get :remove_notification, :on => :member
    post :search, :on => :collection
    get :in_location, :on => :member
    get :in_status, :on => :member
    get :in_type, :on => :member
    post :mail_attachment, :on => :member
    post :mail_note, :on => :member
    get :pdf, :on => :member
    get :remove_contact, :on => :member
    put :add_contact, :on => :member
    post :add_new_contact, :on => :collection
    get :lock, :on => :member
    get :autocomplete_user_fullname, :on => :collection
    resources :notes
    resources :docs do
      put 'move', :on => :collection
      get 'overwrite', :on => :member
    end
    
    resources :checklists
  end
  resources :locations do
    post 'name', :on => :member
    collection do
      put :update_attribute_on_the_spot
      get :get_attribute_on_the_spot
    end
  end
  match 'search/' => 'transactions#search'
  match 'lib/' => 'welcome#lib'
  match 'profile/' => 'welcome#profile'
  match 'dropboxauth/' => 'welcome#dropboxauth', :as => "dropboxauth"
  match 'library' => 'libraries#index'
  match 'dashboard' => 'welcome#dashboard'
  
  
  post 'get_mail' => 'transactions#get_mail'
  get 'te' => 'transactions#te'

	get "home(/:action)", :controller => "pages"

  root :to => 'welcome#index'

end

app/models/transaction_type.rb
class TransactionType < ActiveRecord::Base
  attr_accessible :name, :transaction_detail_id, :checked
  belongs_to :transaction_detail
  has_many :transactions
  has_and_belongs_to_many :checklist_masters
  scope :checked_only, where(:checked => true)
  
  scope :for_company, lambda { |company_id| where("transaction_details.company_id = ?", company_id).includes(:transaction_detail)}
  
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  
  skip_before_filter :authenticate_user!, :only => [:mail_attachment]
  load_and_authorize_resource :except => [:autocomplete_user_fullname, :add_contact, :mail_attachment, :in_location, :in_status, :in_type,  :remove_contact]
  autocomplete :user, :fullname, :display_value => :fullname_email
  before_filter :find_transaction, :only => [:mail_attachment, :pdf, :lock, :add_contact, :edit, :remove_notification, :update, :destroy]
  after_filter :user_extra_params, :only => [:add_contact]
  after_filter :attach_contact, :only => [:add_contact, :add_new_contact]
  after_filter :attach_new_contact, :only => [:create]
  
  def get_autocomplete_items(parameters)
     super(parameters)
     items = User.search_by_fullname(params[:term], current_user.id).select{|c| c.inclede_contacts?(current_user) }
  end
  
  
  
  def mail_attachment
    # process various message parameters:
    
    actual_body = params["body-html"]

    user = User.find_by_mail_digest(recipient.split("-").first)
    @transaction.notes.create(:status => actual_body, :user_id => user.id, :by_mail => true, :mail_it => true, :extra_params => params) unless actual_body.blank? || !user
  
     
    render :text => "OK"
  end
  
  def search
		sort = params[:sort]
		sort = "created_at" if sort == "latest" || sort.blank?
		sort = "close_sate" if sort == "date"
    if params[:search]
			filters = {:name => params[:search], :mls => params[:search], :street => params[:search], :city => params[:search], :county => params[:search], :address_1 => params[:search], :address_2 => params[:search], :state => params[:search], :zip => params[:search]}
			@transaction = Transaction.new(:only_for_search => true)
      @transactions = @transaction.find_by_keyword(filters, @global_company, sort)
    else
			@transaction = Transaction.new(params[:transaction].merge({:only_for_search => true}))
      @transactions = @transaction.find_by_keyword(params[:transaction], @global_company, sort)
    end
    
    render :action => "index"
  end
  
  def index
		sort = params[:sort]
		sort = "created_at" if sort == "latest" || sort.blank?
		sort = "close_sate" if sort == "date"
    
    @transactions = Transaction.where("transactions.user_id IN (?) OR attach_contacts.user_id = ?", current_user.default_ids, current_user.id).includes(:attach_contacts).order("transactions.#{sort} ASC")
    @transaction = Transaction.new()

  end
  
  def in_location
    @transactions = Transaction.where(:location_id => params[:id])
    render :action => "index"
  end
  
  def in_status
    @transactions = Transaction.where(:transaction_status_id => params[:id])
    render :action => "index"
  end
  def in_type
    @transactions = Transaction.where(:transaction_type_id => params[:id])
    render :action => "index"
  end
  
  
  def pdf
    
  end
  # GET /transactions/1
  # GET /transactions/1.json
  def show
    transaction = Transaction.find(params[:id])
    @transaction = transaction.true_for_global(@global_company, current_user) ? transaction : not_found
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end
  
  def lock
    lock = !@transaction.lock?
    @transaction.update_attributes(:lock => lock)
    redirect_to :back
  end
  
  def remove_contact
    ContactAccess.where(:contact_id => params[:id], :user_id => params[:user_id]).destroy_all
    unless params[:attach_contact].blank?
      AttachContact.find(params[:attach_contact]).destroy
    end
    redirect_to :back
  end

  def add_new_contact
    @contact = params[:user] ? User.as_contact(params[:user], current_user.company_id) : User.find_by_first_name_and_last_name(Company.split_name(params[:transaction][:company_name], 0), Company.split_name(params[:transaction][:company_name], 1))
  end
  
  
  def add_contact
    @contact = params[:user] ? User.as_contact(params[:user], current_user.company_id) : User.cuted_contact(params[:transaction][:company_name])
  end
  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @page_title = "New Transaction"
    @transaction = Transaction.new
    @td = @global_company.transaction_details.first
    
    
    
    respond_to do |format|
      format.html {
        if @global_company.transactions_ended?
          redirect_to "/"
        end
      }
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  
  def edit
    @td = @global_company.transaction_details.first
    
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = current_user.transactions.new(params[:transaction])
    
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transactions_path, notice: 'Transaction was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  
  def remove_notification
    
    @ac = AttachContact.find(params[:user_id])
    RecentActivity.create(:transaction_id => @transaction.id, 
                          :user_id =>  current_user.id, 
                          :message =>  "Removed Contact: #{@ac.user.fullname} as #{@ac.role.name if @ac.role}")
    
    render :nothing => true
  end
  
  
  def update
    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end
  
  private
  def user_extra_params
    @existing_user = !@contact.nil? && @contact.existing? ? true : false
  end
  
  def attach_new_contact
    @transaction.attach_contacts.create(:user_id => current_user.id, :role_id => params[:transaction][:my_role]) unless params[:transaction][:my_role].blank?
  end
  
  def attach_contact
    unless @contact.nil?
      @contact.setup_contact_params(current_user, @transaction)
      params[:user] ||= params[:transaction]
      @attach_contact = @contact.attach_contacts.create(:transaction_id => params[:id], :role_id => params[:user][:role_id], :attach_to_transaction => true)
    end
  end
  
  
  def body_mail
    @transaction = Transaction.find(params[:id])
    # process various message parameters:
    @global_sender  = params['sender']
    @global_subject = params['subject']
    @global_recipient = params['recipient']

    # get the "stripped" body of the message, i.e. without
    # the quoted part
    @global_body = params["body-html"]#params["stripped-text"]
  end
  
  
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_documents.html.haml
%table.documents
  %thead
    %tr.headings
      %th File name
      %th Checklist
      -#
        %th Uploaded by 
        %th Date
        
      %th.review-heading
        Review
      %th Actions
      - if current_user.super_admin? || current_user.p_all? || @transaction.user == current_user
        %th Shared
  %tbody#documents
    - @transaction.docs.each do |doc|
      = render "docs/doc", :doc => doc if doc.users.map(&:id).include?(current_user.id) || current_user.super_admin? || current_user.p_all? || @transaction.user == current_user
      

.documents-upload.well.dashed-border#drop_transactions_upload_button
  %button.btn.btn-info.uploader_button{:upload_path => transaction_docs_path(@transaction), :id => 'transactions_upload_button', :upload_container => "documents", :process_view => "doc_process", :after_view => "doc" }
    %i.glyphicon.glyphicon-upload 
    Upload new document
  = mail_to @transaction.user_mail_attachment(current_user), icon("envelope", "Send it via email attachment"), :class => "btn btn-info default_right_padding"
  = icon("arrow-down", "or Drag n Drop here")
    

app/views/transactions/_e_assing_users.html.haml
- main_uid = []
- user_names = []
- @global_company.users.each do |u|
  - lp = @transaction.location.location_permissions.find_by_user_id(u.id)
  - #if (lp && lp.l2?) || u.super_admin? || u.p_all?
  - if u.super_admin? || u.p_all?
    - user_names << u.fullname
- attach_contacts.each do |ac|
  - user = ac.user
  - user_names << user.fullname

%i.glyphicon.glyphicon-user.big{:rel => "tooltip", :title => user_names.join(", "), :class => "assigned_users"}
%span= ""


= render "users/assign_users", :attach_contacts => current_user.attach_contacts
.pull-right
  .btn-group
    %button.btn.btn-info.btn-xs
      = icon("user", "")
    %button.btn.btn-info.btn-xs.dropdown-toggle{"data-toggle" => "dropdown"}
      %span.caret
    %ul.dropdown-menu
      - User.where("(parent_id = ? OR id IN (?)) AND id != ?", current_user.id, @transaction.attach_contacts.map(&:user_id), current_user.id).each do |user|
        %li
          = link_to ms_link_users_shared(user.fullname, user, super_contact), "#", :class => "multicheck #{'checked' if user.contact_accesses.map(&:contact_id).include?(super_contact.id)}", "data-fileid" => user.id
      %li
        .popup_buttons_container
          = link_to icon("ok", "Save"), "#", :class => "btn btn-xs btn-info assign_files_to", "data-url" => assign_contact_user_path(super_contact)
          = link_to icon("share-alt", "Cancel"), "#", :class => "close_assign_files btn btn-xs"

%table.table.table-condensed.table-hover
  %thead
    %tr
      %th{:colspan => 2}
        = contact.role.name if contact.role
  %tbody
    %tr
      %td
        %strong Name:
      %td
        .pull-right
          = "#{contact.first_name} #{contact.last_name}"
    %tr
      %td
        %strong Phone:
      %td
        .pull-right= contact.phone

    %tr
      %td
        %strong Title:
      %td
        .pull-right= contact.info
    %tr
      %td
        %strong Fax:
      %td
        .pull-right= contact.fax
    %tr
      %td
        %strong Email:
      %td
        .pull-right= contact.email

      

app/views/transactions/_filters.html.haml
%h3.heading Filter results

= form_for @transaction, :url => search_transactions_path, :method => :get do |f|

  .field
    
    %label MLS
  
    = f.text_field :mls

  .field
    
    %label Street Address 1
  
    = f.text_field :address_1
  
  .field
    
    %label Street Address 2
  
    = f.text_field :address_2
  
  .field
    
    %label County
  
    = f.text_field :county
  
  .field
    
    %label City
  
    = f.text_field :city
      
  .field
    
    %label State
  
    = state_select(:transaction, :state, 'US', {:include_blank => 'Please Choose'})
      
  .field
    
    %label Status:
  
    = collection_select(:transaction, :transaction_status_id, @global_company.transaction_details.last.transaction_statuses.checked_only, :id, :name, {:prompt => 'Please Choose'})

  .field
    
    %label Location:
  
    = collection_select(:transaction, :location_id, @global_company.locations.all, :id, :name, {:prompt => 'Please Choose'})
         
  -#
    .field
    
      %label Acceptance Date
    
      = f.text_field :acceptance_date_from, :class => "datepicker", :placeholder => "FROM"
      = f.text_field :acceptance_date_to, :class => "datepicker", :placeholder => "TO"
      
  .field
    
    %label Closing Date
 
    = f.text_field :close_sate_from, :class => "datepicker", :placeholder => "FROM"
    = f.text_field :close_sate_to, :class => "datepicker", :placeholder => "TO"
      
  .field
    
    %label Expiration Date

    = f.text_field :expiration_date_from, {:class => "datepicker", :placeholder => "FROM"}
    = f.text_field :expiration_date_to, :class => "datepicker", :placeholder => "TO"
      
  .field
    
    %label List Price
  
    = f.text_field :list_price_from, :class => "price", :placeholder => "FROM"
    = f.text_field :list_price_to, :class => "price", :placeholder => "TO"
    
  .field
  
    %label Sale Price

    = f.text_field :sale_price_from, :class => "price", :placeholder => "FROM"
    = f.text_field :sale_price_to, :class => "price", :placeholder => "TO"
      
  .field
    %button.btn.btn-primary{type: "submit"} Filter Results
    

app/views/transactions/_mini_contact.html.haml
- @transaction.attach_contacts.each do |contact|
  - if current_user.contact_accesses.where(:transaction_id => @transaction.id).map(&:contact_id).include?(contact.user.id) || current_user.super_admin? || current_user.p_all? || @transaction.user == current_user
    %tr
      %td.name
        %strong
          - if contact.user.no_email?
            = contact.user.fullname 
          - else
            = mail_to(contact.user.email, contact.user.fullname)
      %td.role
        = contact.role.name
      %td.company= !contact.user.company.nil? && contact.user.contact_company.blank? ? contact.user.company.name : contact.user.contact_company
      
      %td.phone= contact.user.phone
      - if current_user.super_admin? || current_user.p_all? || @transaction.user == current_user
        %td#assign_users_process_div
          = render "users/assign_users_process", :attach_contacts => current_user.attach_contacts, :super_contact => contact.user

app/views/transactions/_overview-box-mock.html.haml
%a.transaction-box{href: "#"}
  
  %span.photo.data{style: "background-image: url(#{image_path("transactions/no-photo.jpg")})"}

  %span.information
    %span.glyphicon.glyphicon-info-sign{title: (render "transactions/tooltip-information-mock").html_safe, data: {toggle: "html-tooltip", placement: "top"}}
  
  %span.address.data
    2552 Poplar Ave, Memphis, Tennessee
      
  %span.status.data{class: status.downcase}
    = status.capitalize
    
  %span.checklist.data{title: (render "transactions/tooltip-checklist-mock").html_safe, data: {toggle: "html-tooltip", placement: "top"}}
    %span.label.label-default
      %span.number 8 / 12
      %span.progress-bar{:style => "width:50%"}
  
  %span.location.data
    Main Office
  
  %span.date.data
    24 Dec 2013

app/views/transactions/_tooltip-checklist-mock.html.haml
%h4.heading Items to do
%ol
  - %w{Buy Sell}.each do |ch|
    %li= ch

app/views/transactions/_transaction.html.haml
- unless disable_access(:read, transaction)
  %tr
    %td= link_to tname(@global_company.transaction_details.first, transaction), transaction_path(transaction)
    %td
      %span.label.label-success= transaction.transaction_status.name if transaction.transaction_status
    - unless current_user.real_guest?
      %td{ "data-value" => (bar_width(transaction.checklist_items.length, transaction.checklist_items.checked_only.length) / 10) }
        .progress{:class => "super_tooltip", :title => render("welcome/transaction_info", :transaction => transaction).html_safe}
          %span= "#{transaction.checklist_items.checked_only.length} / #{transaction.checklist_items.length}"
          .progress-bar{:style => "width: #{bar_width(transaction.checklist_items.length, transaction.checklist_items.checked_only.length)}%;"}
         
    
      %td
        - users_map = transaction.attach_contacts.map{|c| "#{c.user.fullname} (#{c.role.name})"}.join(", ")
        - unless users_map.empty?
          %i.glyphicon.glyphicon-user.big{:rel => "tooltip", :title => users_map || "", :class => "assigned_users"}
    %td= transaction.location.name if transaction.location
    %td= transaction.close_sate.strftime('%b %d, %Y') unless transaction.close_sate.blank?

app/views/transactions/edit.html.haml
.row
  .col-md-12
    %h1= "Edit #{tname(@global_company.transaction_details.first, @transaction)}"
.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        %h3.panel-title Transaction Details
      .paddedpanel
        = render "form"
  .col-md-6
    .panel.panel-default
      .panel-heading
        %h3.panel-title Contacts
      .paddedpanel
        = render "contacts/transaction", :transaction => @transaction
          
        .row
          .outside_agents_well.hidden_item.defailt_padding
            = render "contacts/new_form_add"
    

.row.defailt_padding
  .col-md-12
    %button.btn.btn-info.save_transaction
      %i.glyphicon.glyphicon-ok 
      Save
    = link_to icon("share-alt", "Cancel"), transaction_path(@transaction), :class => "btn btn-default"
    - unless disable_access(:destroy, @transaction)
      = link_to icon("trash", "Delete Transaction"), transaction_path(@transaction), :method => :delete, :confirm => 'Are you sure?', :class => "btn btn-danger"

app/views/transactions/show.html.haml
- @body_class = "transaction-detail"

.page-header

  %h1.heading
    = tname(@global_company.transaction_details.first, @transaction)
  
  .actions
    
    -#
      - if @transaction.lock?
        = link_to icon("lock", "Transaction is locked"), lock_transaction_path(@transaction), class: "btn btn-default"
      - else
        = link_to icon("unlock", "Transaction is unlocked"), lock_transaction_path(@transaction), class: "btn btn-default"
    
    - unless disable_access(:update, @transaction)
      = link_to icon("pencil", "Edit Transaction"), edit_transaction_path(@transaction), :class => "btn btn-default", :disabled => disable_access(:update, @transaction)

- if @global_company.transaction_details.first.only_pdf?
  //%a#pdf_only{:mark => "a"}
- if @transaction.lock? && (!current_user.super_admin? || disable_access(:assign_files, @transaction))
  %a#lock-transaction{:mark => "a"}


.row
  
  .col-md-3
    
    - location_permissions = @transaction.location.location_permissions.find_by_user_id(current_user.id)
    - if (location_permissions.l12? && @transaction.user == current_user) || location_permissions.l2? || (current_user.super_admin? || current_user.p_all?)
      .transaction-box
        %span.photo.data{style: "background-image: url(#{image_path("transactions/no-photo.jpg")})"}

    
    .details
      .detail
        %span.detail-label Location
        %span.detail-number= @transaction.location.name if @transaction.location
      .detail
        %span.detail-label List Price
        %span.detail-number=number_to_currency @transaction.list_price, :precision => 0 unless @transaction.list_price.blank?
      .detail
        %span.detail-label Sale Price
        %span.detail-number=number_to_currency @transaction.sale_price, :precision => 0 unless @transaction.sale_price.blank?
      .detail
        %span.detail-label Added on
        %span.detail-number= @transaction.created_at.strftime('%b %d, %Y')
      .detail
        %span.detail-label Closing
        %span.detail-number= @transaction.close_sate.strftime('%b %d, %Y') unless @transaction.close_sate.blank?
      .detail
        %span.detail-label Expiring
        %span.detail-number= @transaction.expiration_date.strftime('%b %d, %Y') unless @transaction.expiration_date.blank?
    
    .checklists
      %h4.heading Checklists
      - @transaction.checklists.each do |checklist|
        = render "checklists/checklist", :checklist => checklist
      
      .checklist-actions
    
        - unless disable_access(:add_remove_checklists, @transaction)
          %button.btn.btn-default.btn-xs.add_an_checklist
            .glyphicon.glyphicon-add
            Add a Checklist
      .add-checklist.add_an_checklist_well{style: "display: none"}
        = render "checklists/form", :transaction => @transaction
  
  .col-md-9
    
    .page-sub-header

      %h2.heading
        Recent Activity
    
    .panel
      .panel-body
        
        %table#activities.activities
          - @transaction.recent_activities.order("created_at DESC").limit(10).each_with_index do |ra, index|
            - unless current_user.real_guest? && !current_user.p_all? && ra.note_id.blank?
              - unless !ra.note_id.blank? && !current_user.p_all?  && !current_user.super_admin? && !ra.note.for_users.split(",").include?(current_user.id.to_s) && ra.note.user != current_user
                %tr.activity{class: ("hidden" if index >= 3)}
                  %td.avatar= image_tag ra.user.def_avatar, :size => "40x40"
                  %td.name= ra.user.fullname
                  - message = ra.message.gsub("Transaction", "#{link_to("Transaction (#{tname(@global_company.transaction_details.first, ra.transaction)})", "#")}")
                  %td.message= message.gsub("Close sate", "Close date").html_safe
                  %td.time= "#{time_ago_in_words(ra.created_at)} ago"

    .page-actions
      
      - if @transaction.recent_activities.count > 3
        %a.btn.btn-default.show-more{href: "#show-more", data: {show: "#activities"}}
          .glyphicon.glyphicon-chevron-down
          %span.text Show more
    
    
    -#
      - unless current_user.real_guest? || @global_company.real_free?
        .page-sub-header

          %h2.heading
            Checklists
    
        .panel
          .panel-body
        
            - @transaction.checklists.each do |checklist|
              = render "checklists/checklist", :checklist => checklist

        .page-actions
      
          - unless disable_access(:add_remove_checklists, @transaction)
            %button.btn.btn-default.add_an_checklist
              .glyphicon.glyphicon-add
              Add a Checklist
        
    
      .add-checklist.add_an_checklist_well{style: "display: none"}
        = render "checklists/form", :transaction => @transaction
    

    .page-sub-header

      %h2.heading
        Contacts
    
    .panel
      .panel-body
        = render "contacts"
  
    .add-contact.add_an_contact_well{style: "display: none"}
      = render "contacts/form_add"

    .page-actions
      - unless disable_access(:update, @transaction)
        %button.btn.btn-default.add_an_contact
          .glyphicon.glyphicon-add
          Add a Contact
    
    .add-note.add_an_note_well{style: "display: none"}
      = render "notes/form"


    
    .page-sub-header

      %h2.heading
        Documents

      .actions
      
        %button.btn.btn-default.uploader_button{:upload_path => transaction_docs_path(@transaction), :id => 'transactions_upload_button_top', :upload_container => "documents", :process_view => "doc_process", :after_view => "doc" }
          %i.glyphicon.glyphicon-upload 
          Upload Document
      
        %a.btn.btn-default{href: "mailto:#{@transaction.user_mail_attachment(current_user)}"}
          .glyphicon.glyphicon-add
          Email a Document
    
    .panel
      .panel-body
        
        #documents= render "documents"
    
    .page-actions
    
    
    
    .page-sub-header

      %h2.heading
        Notes

      .actions
      
        %button.btn.btn-default.add_an_note
          .glyphicon.glyphicon-add
          Add a Note
      
        -#
          %a.btn.btn-default{href: "mailto:#{@transaction.user_mail_attachment(current_user)}"}
            .glyphicon.glyphicon-add
            Email a Note
    
    .panel
      .panel-body
        
        #notes.notes
          - @transaction.notes.each_with_index do |note, index|
            .well{class: ("hidden" if index >= 3)}
              .author
                = image_tag note.user.def_avatar, :size => "40x40", :class => "avatar"
                %span.name= note.user.fullname
              .time
                = "#{time_ago_in_words(note.created_at)} ago"
              .message
                = note.note_message.html_safe if note.note_message.present?
                %pre.message-body= truncate(note.status, length: 250) if note.status

    .page-actions
      
      - if @transaction.notes.count > 3
        %a.btn.btn-default.show-more{href: "#show-more", data: {show: "#notes"}}
          .glyphicon.glyphicon-chevron-down
          %span.text Show more